### ISSUE TITLE
Specifying Dates

### ISSUE THREAD

**Issue by 2e0byo** [2e0byo/YADC#2]
[Moved from a closed issue]

hi 2e0byo
I hope this is the right place to ask this.

In the main.py bit of code, i have a query on how to specify dates:

```python
driver = Driver(
    licence_number="YOUR_NUMBER",
    booking_ref="YOUR_REF",
    not_before=datetime(2021, 12, 10),
    not_after=datetime(2022, 3, 1),
    centres=[
        Centre(centre="Gateshead", before=datetime(2022, 1, 1)),
        Centre(centre="Durham"),
    ],
)
```
Lets say a test is booked for 15/01/2021
what would the datetime configuration be to look for dates after the booked test? say between 01/03/21 and 01/04/2021
Also im not sure what the before=datetime(2022, 1, 1) means in the centres list as its possibly defined earlier in the not_before... section?
Any advice would be much appreciated.

_Originally posted by @chrishat34 in https://github.com/2e0byo/YADC/issues/1#issuecomment-980182820_

**Comment by 2e0byo** [comment]
I guess I could have documented these better.

`not_before` specifies the date after which we start looking (i.e. we don't want tests tomorrow).

`not_after` specifies the date after which we give up looking.

However, for every particular centre, we only look for tests which are newer than our *current* test, by default.  But it might be that we would rather have a test in centre A before the 20th Dec than have a test in centre B on the 10th.  So for every centre, if we have specified a `before=`, we consider all tests which fall before that particular date.  If we find one we pause and ask the user what to do.  If `before=` is *not* specified, we only consider tests before our *current* test date.

The functionality this implements couuld definitely be implemented better; this was just the quickest way.  The original logic assumed we just wanted the nearest available test.

> what would the configuration be to look for dates after the booked test?

Set a `before` for the centre in question with a date the day *after* you want to look up to.  so for yours, set `before=datetime(2022,4,2)`.  This will override the current booked test date (which is scraped from the page when it logs in).  Then set your global `not_before` and `not_after` values correctly.

This is also not the best logic in the world.  If this is a use case, I'll implement it a bit better.

**Comment by chrishat34** [comment]
That's great, thank you, i'll try that.

**Comment by chrishat34** [comment]
Hi, 
line 394 in yadc.scraper.py
before_date = driver.current_test.date or centre.date
suggest driver.current_test.date and centre.date are swapped back around ....... as i understand it python returns the 1st true value and centre.date will never trigger as there is always a driver.current_test.date
Also centre.date returns none (even when it is set in main.py for a particular centre like:
```python
driver = Driver(
    licence_number="xxxxxxxxx",
    booking_ref="xxxxxxxx",
    not_before=datetime(2021, 7, 10),
    not_after=datetime(2022, 12, 1),
    name="Roger t looking for after his current date date of 28/06/2022",
    centres=[
        Centre(centre="carlisle", before=datetime(2022,12,1)),
    ],
)
```
i have tried to define centre.date so it does return the value but to no avail, sorry.

**Comment by 2e0byo** [comment]
Looks like I didn't properly finish the logic here.  I've rewritten it so that `Centre`s can take a `not_before` and `not_after`, which overrides the driver's if set.

The failure to find anything after the current test was a logic error.  It now only considers the current test if it's after the not_before set, so you can use it to find tests after the current test (hopefully)---albeit the logic will try to craw as close as possible to the `not_before`.

Note that the tests have just failed for an unrelated reason (tor seems to have moved upstream, so I'll need to update the script which downloads it for the tests).

Let me know if this works.

**Comment by 2e0byo** [comment]
released now in v0.16.3.  However, untested.

**Comment by chrishat34** [comment]
Thank you for this, just one typo i think, yadc.scraper.py line 416
if date < not_before: # was before:

ok, gets as far as trying to reserve, i have added an extended screen dump as originating one didn't show the attempted reserve bit
![error-2022-03-18_10-00-50](https://user-images.githubusercontent.com/43535243/158984031-26fc9436-0a8e-400d-9818-6dab163c769c.png)
[error-2022-03-18_10-00-50.txt](https://github.com/2e0byo/YADC/files/8303584/error-2022-03-18_10-00-50.txt)
[extended_traceback.txt](https://github.com/2e0byo/YADC/files/8303585/extended_traceback.txt)
[error-2022-03-18_10-00-50_html.txt](https://github.com/2e0byo/YADC/files/8303601/error-2022-03-18_10-00-50_html.txt)
.
```python
driver = Driver(
    licence_number="TREAD904195RB9ML",
    booking_ref="50332477",
    not_before=datetime(2022, 8, 2),
    not_after=datetime(2022, 8, 4),
    name="Roger t looking for after his current date date of 28/06/2022",
    centres=[
        Centre(centre="carlisle", not_after=datetime(2022,12,1)),
    ],
)
```

**Comment by chrishat34** [comment]
but these details did go through and reserve a date of 18th may at 14:32

driver = Driver(
    licence_number="xxxxx",
    booking_ref="xxxxx",
    not_before=datetime(2022, 3, 24),
    not_after=datetime(2022, 8, 4),
    name="Roger t looking for after his current date date of 28/06/2022",
    centres=[
        # Centre(centre="carlisle", not_after=datetime(2022,12,1)),
        Centre(centre="carlisle"),
    ],
)
