### ISSUE TITLE
Cannot connect to chrome - Chromedriver version error

### ISSUE THREAD

**Issue by chrishat34** [2e0byo/YADC#7]
Since the latest Chrome update - YADC appears to not load up anymore - I'm investigating.
Here is the error message:
2022-02-04 06:11:15 chris-X202EP Browser-1[3035] INFO Starting search loop
2022-02-04 06:11:15 chris-X202EP Browser-1[3035] INFO Starting Tor
2022-02-04 06:11:16 chris-X202EP Browser-1[3035] INFO Started Tor
2022-02-04 06:11:27 chris-X202EP undetected_chromedriver.patcher[3035] INFO patching driver executable /home/chris/.local/share/undetected_chromedriver/chromedriver
2022-02-04 06:11:29 chris-X202EP Browser-1[3035] ERROR Message: unknown error: cannot connect to chrome at 127.0.0.1:38393
from session not created: This version of ChromeDriver only supports Chrome version 98
Current browser version is 97.0.4692.99

**Comment by 2e0byo** [comment]
> Current browser version is 97.0.4692.99

Is it getting the wrong chrome?  Or is your system chrome 97?

**Comment by chrishat34** [comment]
The above error was on a linux build. 
Back to windows now:
current windows chrome @
    Chrome is up to date
    Version 98.0.4758.81 (Official Build) (64-bit)
Chromedriver.exe @ 
    If you are using Chrome version 98, please download [ChromeDriver 98.0.4758.80]
and getting the error as
    selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at localhost:54421
    from session not created: This version of ChromeDriver only supports Chrome version 96
    Current browser version is 98.0.4758.81
We are able to open the correct DVSA url but then this error message and goes on to open multiple windows of the same.
I would think this is very much the chromedriver and/chrome being out of synch somehow and probably the .81 compared to .80 -  No changes to the code have taken place.

**Comment by 2e0byo** [comment]
looks like it's really that picky.  The page opens first before the chromedriver connects, so that's why it works.  Sadly it seems you'll have to download another chromedriver, however I can't see where to get .81 chromedriver!  Maybe it's worth upgrading to chrome{, driver} 99?  [chrome beta](https://www.google.com/intl/en_uk/chrome/beta/?platform=win64) [chromedriver 99](https://chromedriver.chromium.org/downloads) ?

I can't reproduce locally with chrome/driver @ 98.0.4758.80 on linux.

**Comment by 2e0byo** [comment]
Incidentally this is much easier to fix on linux.  something like arch has real packages and you just do `pacman -S chromium-chromedriver`.  But ubuntu has decided to go with snap, so you should get chromedriver [just by installing the snap package](https://snapcraft.io/install/chromium/ubuntu).

Installing software with the system package manager should keep versions in sync.

**Comment by chrishat34** [comment]
Chromedriver eventually sorted - it was that fussy!!
