### ISSUE TITLE
Can't find the file specified

### ISSUE THREAD

**Issue by akZiino** [2e0byo/YADC#9]
![image](https://user-images.githubusercontent.com/100000997/156629366-705632e5-fc49-471d-b49b-8c42add70711.png)
 Any idea how I can fix this?

Thanks

**Comment by 2e0byo** [comment]
Did you supply the correct path to `tor.exe`?

**Comment by akZiino** [comment]
I'm not sure where to pass the tor directory

**Comment by akZiino** [comment]
> 

Thank you. After adding the tor path, I get then following: 
![image](https://user-images.githubusercontent.com/100000997/156891836-fe0ffe3f-c27a-438c-b807-f8f118475796.png)


a Tor browser opens but nothing else happens. I've dropped chromedriver.exe into the folder

**Comment by 2e0byo** [comment]
Yes, Windows is finicky.  You need at least the complete relative path (ending with the full filename, I.e. .exe) although the full absolute path is easier.

I'll add some proper docs when I get a moment.

**Comment by 2e0byo** [comment]
Did you get this going?

**Comment by minhhieutran2112** [comment]
Hi I am using Windows as well. And it does not seem to be able to connect to the internet when using Tor proxy, do you know why this is the case?

Thanks!

**Comment by 2e0byo** [comment]
I think this repo could really do with a FAQ.  I'll make one.

**Comment by 2e0byo** [comment]
I have added an FAQ which should cover this problems in this issue in https://github.com/2e0byo/YADC/commit/86502ae88c147975b06ad091ab399b01a1cef9a0.  I'm goiing to close this issue as there's been no response from the OP for a while, and @minhhieutran2112's issue is not obviously related to the title.  Feel free either to reopen this issue (for it's original purpose) or to make a new issue if need be.
